---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rolling-update-from-pods
  namespace: r-updated
rules:
# Just an example, feel free to change it
# Check the core API group e.g., deployments are
# only availabe from the apps API group since v1.16
 - apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolling-update-from-pods
  namespace: r-updated
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: rolling-update-from-pods
  apiGroup: rbac.authorization.k8s.io
