---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rolling-update-from-pods
  namespace: r-updated
rules:
# Just an example, feel free to change it
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rolling-update-from-pods
  namespace: r-updated
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: rolling-update-from-pods
  apiGroup: rbac.authorization.k8s.io
